# Generated by Django 3.1.2 on 2020-12-03 15:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20201202_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 3, 18, 35, 54, 524465)),
        ),
    ]
