# Generated by Django 3.1.2 on 2020-12-06 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20201203_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 6, 18, 43, 44, 104725)),
        ),
    ]
